serverId: default
role: monolith

apiServer:
  port: 8080
  publicHost: 0.0.0.0
  publicPort: 8080
  publicScheme: http

insightsServer:
  port: 8081
  publicHost: 0.0.0.0
  publicPort: 8081
  publicScheme: http

webServer:
  port: 8080
  publicHost: 0.0.0.0
  publicPort: 8080
  publicScheme: http

logging:
  mode: normal

database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  name: ${DATABASE_NAME}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  requireSsl: true
