apiServer:
  port: 8080
  publicHost: 0.0.0.0
  publicPort: 8080
  publicScheme: http

insightsServer:
  port: 8081
  publicHost: 0.0.0.0
  publicPort: 8081
  publicScheme: http

webServer:
  port: 8082
  publicHost: 0.0.0.0
  publicPort: 8082
  publicScheme: http

webServer:
  port: 8080
  host: 0.0.0.0
    publicScheme: http
