name: nexa_serverpod_client
description: Starting point for a Serverpod client.

environment:
  sdk: '^3.8.0'

resolution: workspace

dependencies:
  serverpod_auth_idp_client: 3.3.0
  serverpod_client: 3.3.0
